apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: drj8887tc-python-gitops
  description: This is GitOps manifest for drj8887tc-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: drj8887tc-python
    backstage.io/kubernetes-id: drj8887tc-python 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: drj8887tc-python   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:drj8887tc-python
